server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**

        - id: ACCOUNT-MANAGEMENT
          uri: lb://ACCOUNT-MANAGEMENT
          predicates:
            - Path=/accounts/**
            
        - id: CUSTOMER-ACCOUNT-BANK
          uri: lb://CUSTOMER-ACCOUNT-BANK
          predicates:
            - Path=/linkaccountcustomers/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka