pipeline {
agent any

tools{
maven "MAVEN_HOME"
}



stages {

stage("Checkout code"){
steps
{

echo 'Check Out'
}
}
stage('Clean') {
steps {
bat 'mvn -f Assignment9/LibraryManagementMVC/pom.xml clean'
echo 'Cleaning..'
}
}
stage('Compile') {
steps {
bat 'mvn -f Assignment9/LibraryManagementMVC/pom.xml compile'
echo 'Compiling..'
}
}
stage('Test') {
steps {
bat 'mvn -f Assignment9/LibraryManagementMVC/pom.xml test'
echo 'Testing..'
}
}
stage('Packaging') {
steps {
bat 'mvn -f Assignment9/LibraryManagementMVC/pom.xml package'
echo 'Packageing..'
}
}
stage('Install') {
steps {
bat 'mvn -f Assignment9/LibraryManagementMVC/pom.xml install'
echo 'Installing..'
}
}


}
}